on:
  push:
  workflow_dispatch:

jobs:
  random_y:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: install deps
        working-directory: ./test
        run: yarn install --frozen-lockfile

      - name: install playwright deps
        working-directory: ./test
        run: npx playwright install-deps

      - name: random y
        working-directory: ./test
        run: |
          for i in {1..20}; do
            npx node get_bounding_box.js
          done
